version: "3"
services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    volumes:
      - ./front:/app/
    entrypoint: npm run dev
  back:
    build:
      context: ./back
      dockerfile: Dockerfile.dev
    volumes:
      - ./back:/app/
    entrypoint: npm run dev