version: "3"
services:
  front:
    build:
      context: ./front
  back:
    build:
      context: ./back
    ports:
      - 3001:3001
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/:/etc/nginx/conf.d
    